# Generated by Django 4.1.7 on 2023-02-27 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RiteWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Post',
            new_name='Food',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'ministers'), ('Customer', 'Customer')], default='Customer', max_length=10),
        ),
    ]
