# Generated by Django 4.1.7 on 2023-03-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0003_chopfood_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chopfood_Post',
        ),
    ]
