# Generated by Django 4.1.7 on 2023-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0006_remove_food3_writer_remove_food4_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
