# Generated by Django 4.1.7 on 2023-03-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0007_food_title1_alter_food_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='title1',
        ),
        migrations.AddField(
            model_name='food',
            name='body2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body7',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='body8',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
