# Generated by Django 4.1.7 on 2023-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0008_remove_food_title1_food_body2_food_body3_food_body4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
