# Generated by Django 4.1.7 on 2023-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0009_food_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images2_uploaded'),
        ),
    ]
