# Generated by Django 4.1.7 on 2023-03-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0010_alter_food_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image2',
            new_name='img2',
        ),
    ]
