# Generated by Django 4.1.7 on 2023-03-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0011_rename_image2_food_img2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='image_one',
        ),
        migrations.RemoveField(
            model_name='food',
            name='img2',
        ),
        migrations.AddField(
            model_name='food',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
