# Generated by Django 4.1.7 on 2023-03-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0012_rename_image_food_image_one_remove_food_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image_two',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_uploaded')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.food')),
            ],
        ),
    ]
