# Generated by Django 4.1.7 on 2023-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0013_remove_food_image_one_remove_food_image_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
        migrations.DeleteModel(
            name='FoodImage',
        ),
    ]
