# Generated by Django 4.1.7 on 2023-03-16 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RiteWeb', '0014_alter_food_image_delete_foodimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Food2',
        ),
    ]
