# Generated by Django 4.1.7 on 2023-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0017_ewedding_erendering_eplanning_enaming_ehotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eplanning',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_uploaded'),
        ),
    ]
