# Generated by Django 4.1.7 on 2023-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0018_eplanning_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eplanning',
            name='video',
        ),
    ]
