# Generated by Django 4.1.7 on 2023-03-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0020_alter_eanniversary_body_alter_eanniversary_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eanniversary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ebirthday',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ehotel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='enaming',
            name='title',
        ),
    ]
