# Generated by Django 4.1.7 on 2023-03-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0021_remove_eanniversary_title_remove_ebirthday_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecafeteria',
            name='title',
        ),
        migrations.RemoveField(
            model_name='erendering',
            name='title',
        ),
    ]
