# Generated by Django 4.1.7 on 2023-03-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alcholic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rites9',
            new_name='tools',
        ),
    ]
