# Generated by Django 4.1.7 on 2023-03-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealCanteen', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rite2',
            new_name='rite',
        ),
    ]
