# Generated by Django 4.1.7 on 2023-03-07 15:47

import RiteCanteen.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodSecondPage_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=RiteCanteen.models.save_subject_image, verbose_name='Food Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('Foodfirstpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodsecondpage', to='RiteCanteen.foodfirstpage')),
            ],
        ),
        migrations.CreateModel(
            name='FoodContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodContent_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=200, null=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Hymn.')),
                ('slug', models.SlugField(blank=True, max_length=90, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('FoodFirstPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiteCanteen.foodfirstpage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foodsecondpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcontent', to='RiteCanteen.foodsecondpage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
