# Generated by Django 4.1.7 on 2023-03-10 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0003_remove_continental_body_remove_continental_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commenter', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('rite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='RiteCanteen.continental')),
            ],
        ),
    ]
