# Generated by Django 4.1.7 on 2023-03-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0005_alter_continental_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continental',
            old_name='body2',
            new_name='body',
        ),
    ]
