# Generated by Django 4.1.7 on 2023-03-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0007_continental2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rite',
        ),
        migrations.AddField(
            model_name='comment',
            name='love',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='RiteCanteen.continental2'),
            preserve_default=False,
        ),
    ]
