# Generated by Django 4.1.7 on 2023-03-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0013_rename_commenter_comment_commenter2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Commenter2',
            new_name='Commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='love',
        ),
        migrations.AddField(
            model_name='comment',
            name='rite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='RiteCanteen.continental'),
        ),
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commenter2', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('love', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments2', to='RiteCanteen.continental2')),
            ],
        ),
    ]
