# Generated by Django 4.1.7 on 2023-03-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0015_delete_comment2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continental2',
            old_name='slug',
            new_name='slug2',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
