# Generated by Django 4.1.7 on 2023-03-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0016_rename_slug_continental2_slug2_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continental2',
            old_name='slug2',
            new_name='slug',
        ),
    ]
