# Generated by Django 4.1.7 on 2023-03-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0017_rename_slug2_continental2_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continental2',
        ),
    ]
