# Generated by Django 4.1.7 on 2023-03-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0020_rename_rite_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='rite',
        ),
    ]
