# Generated by Django 4.1.7 on 2023-03-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0021_rename_post_comment_rite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rite',
            new_name='post',
        ),
    ]
