# Generated by Django 4.1.7 on 2023-03-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0023_rename_post_comment_fish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fish',
            new_name='post2',
        ),
    ]
