# Generated by Django 4.1.7 on 2023-03-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0024_rename_fish_comment_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodContent',
        ),
    ]
