# Generated by Django 4.1.7 on 2023-03-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0025_delete_foodcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodSecondPage',
        ),
    ]
