# Generated by Django 4.1.7 on 2023-03-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0026_delete_foodsecondpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodFirstPage',
        ),
    ]
