# Generated by Django 4.1.7 on 2023-03-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0027_delete_foodfirstpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
