# Generated by Django 4.1.7 on 2023-03-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteCanteen', '0029_drunk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drunk',
        ),
    ]
