# Generated by Django 4.1.7 on 2023-03-19 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RiteCanteen', '0030_delete_drunk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pestrils',
            new_name='Pastrils',
        ),
    ]
